#!/bin/bash


## 用法
#clonePHP laravel

# #安裝需要的套件
# yum -y install php-xml rsyslog
# systemctl start rsyslog
# systemctl restart php-fpm
# cls


# ## 專案 位置
# cd ~/www
# cloneX $1
# ############# 專案名稱
# cd ~/www/$1
# composer install 



# ## 資料庫
# rm -rf  .env
# wget https://raw.githubusercontent.com/moon-start/SH/master/binSHHconf/.env


# ## 修改權限
# # chownPHP $1
# #### 修改目錄的 權限
# chown -R nginx ../
# semanage fcontext -a -t httpd_sys_rw_content_t "/usr/share/nginx/html/$1/storage(/.*)?"
# semanage fcontext -a -t httpd_sys_rw_content_t "/usr/share/nginx/html/$1/resources(/.*)?"
# restorecon -Rvv ../


# ## 更新KEY
# phpKEY

## Nginx目錄 設定檔
## [改變 nginx]的 default.conf
DefaultConf.sh  $1







# ##  設定 mysql 環境
# yum install php-mysqlnd
# systemctl restart php-fpm
# ## 查詢 httpd_can_network_connect_db
# # getsebool -a | grep 'httpd'
# setsebool httpd_can_network_connect_db 1
