#!/bin/bash

#安裝需要的套件
yum -y install php-xml rsyslog
systemctl start rsyslog
systemctl restart php-fpm
cls


############# 專案名稱
cd ~/www/$1
# composer create-project --prefer-dist laravel/laravel PHPproject
# 在專案底下?
########
composer install 



## 在專案頂層目錄
rm -rf  .env
wget https://raw.githubusercontent.com/moon-start/SH/master/binSHHconf/.env

## 修改權限
chownPHP $1


## 更新KEY
phpKEY



DefaultConf.sh  $1
