#!/bin/bash



################# 修改配置
##

## 取得上層目錄 #########
cd  /etc/nginx123
QQ=`pwd`
#QQA=${QQ##*/}

if   [ "$QQ" = "nginx" ]
then
    if   [ "$#" = "1" ]
    then
        ########################
        ##
        ## 改變 nginx
        mkdir -p  /etc/nginx/conf.d
        cd  /etc/nginx/conf.d
        rm -rf  ./*
        rm -rf  default.conf
        wget https://raw.githubusercontent.com/moon-start/SH/master/binSHHconf/default.B.conf


        ## 修改檔案
        mv      default.B.conf   default.conf
        sed -i "s/專案名稱/$1/g"  default.conf


        ## 修改檔案
        cd ..
        rm -rf  ./nginx.conf
        wget https://raw.githubusercontent.com/moon-start/SH/master/binSHHconf/nginx.conf


        ## 重新啟動
        nginx -t
        ##################################
        # 避免 nginx: [error] invalid PID number "" in "/run/nginx.pid"
        nginx -c /etc/nginx/nginx.conf
        nginx -s reload
    else 
        echo ""
        echo "說明 [指令] [nginx root目錄]"
        echo ""
else
    echo ""
    echo "cd /etc/nginx 失敗"
    echo "請確認 nginx 安裝!!"
    echo ""