#!/bin/bash
## PID 刪除
# ps aux | grep "clonePHP"
## 強制刪除
# kill -9 15150


## 用法
#clonePHP laravel

## 修改 nginx配置

## 修改 Nginx 目錄
## 改變 nginx
cd  /etc/nginx/conf.d
rm -rf  default.conf

wget https://raw.githubusercontent.com/moon-start/SH/master/binSHHconf/default.C.conf

## 修改檔案
mv      default.C.conf   default.conf

## 下載 nginx.conf
cd ..
wget https://raw.githubusercontent.com/moon-start/SH/master/binSHHconf/nginx.conf


#### PHP設定檔
rm -rf /etc/php-fpm.d/www.conf
cd /etc/php-fpm.d
wget https://raw.githubusercontent.com/moon-start/SH/master/binSHHconf/www.conf
chmod 644 /etc/php-fpm.d/www.conf
## cd ~/
## 重新
systemctl start php-fpm
systemctl restart php-fpm

nginx -t
nginx -s reload


#安裝需要的套件
yum -y install php-xml rsyslog
systemctl start rsyslog
cls



## 假設尚未安裝
#cd ~/www
#cloneX $1
############# 專案名稱
#cd ~/www/$1
# composer create-project --prefer-dist laravel/laravel PHPproject
# 在專案底下?
########
cd /usr/share/nginx/html/
rm -rf ./laravel
git clone https://github.com/moon-start/laravel.git
cd ./laravel
composer install 



## 不太適合用 wget ...改用 git clone?
### 指令設計 在composer專案 
###################### 建議寫在XP專案 一起上傳
## 在專案頂層目錄
rm -rf  .env
wget https://raw.githubusercontent.com/moon-start/SH/master/binSHHconf/.env


## 修改權限
# chownPHP $1
#### 修改目錄的 權限
chown -R nginx ../
semanage fcontext -a -t httpd_sys_rw_content_t "/usr/share/nginx/html/laravel/storage(/.*)?"
semanage fcontext -a -t httpd_sys_rw_content_t "/usr/share/nginx/html/laravel/resources(/.*)?"
restorecon -Rvv ../


## 更新KEY
php artisan key:generate



# ######  不要使用了
# ######
# ## 不太適合用 wget ...改用 git clone?
# ## blade.tar CSS
# ## TAR 檔案的布置
# cd /root/www/$1/resources/views
# wget https://raw.githubusercontent.com/moon-start/SH/master/binTAR/blade.tar
# tar xvf blade.tar
# rm -rf  blade.tar




##  設定 mysql 環境
yum install php-mysqlnd
systemctl restart php-fpm
## 查詢 httpd_can_network_connect_db
# getsebool -a | grep 'httpd'
setsebool httpd_can_network_connect_db 1

###############
############### 安裝 cuth
composer update
composer dump-autoload
composer require laravel/ui --dev  ## 方法B
## 如果錯誤修改這個   composer.json  "require": 
## 使用 ul
## 專案/resources/views/auth
## 產生............[auth/login.blade.php ..等等文件
php artisan ui vue --auth
composer require npm
#yum install nodejs
## 安裝 相關的檔案 [app.css ... app.js]
#/css/app.css   177 KiB  /js/app  [emitted]  /js/app
#/js/app.js  1.39 MiB  /js/app  [emitted]  /js/app
npm install && npm run dev



########
######## 必須 建立好一個 moon
########
######## CREATE DATABASE moon;
php artisan migrate
setsebool httpd_can_network_connect_db 1
