#!/bin/bash



## 安裝 
cd /usr/share/nginx/html
# wget https://files.phpmyadmin.net/phpMyAdmin/4.9.1/phpMyAdmin-4.9.1-all-languages.tar.gz
wget https://raw.githubusercontent.com/moon-start/SH/master/binSHHconf/phpMyAdmin-4.9.1-all-languages.tar.gz


## 解壓縮
tar zxvf phpMyAdmin-4.9.1-all-languages.tar.gz
mv phpMyAdmin-4.9.1-all-languages Admin