#!/bin/bash

yum install wget
    
wget https://getcomposer.org/installer -O composer-installer.php
#wget -y https://getcomposer.org/installer -O composer-installer.php ## 錯誤

php composer-installer.php --filename=composer --install-dir=/usr/local/bin
rm -rf composer-installer.php