#!/bin/bash
systemctl enable --now cockpit.socket
yum -y install epel-release
#systemctl status cockpit.socket

## 安裝 客戶端和伺服器端
yum -y install mysql mysql-server

## 附加一行
echo default-authentication-plugin=mysql_native_password>>/etc/my.cnf.d/mysql-server.cnf

## 自動啟用	
systemctl enable --now mysqld
啟動 MySQL 服務，並修改預設密碼
#systemctl start mysqld
#mysql_secure_installation
#firewall-cmd --add-service=mysql
#firewall-cmd --runtime-to-permanent
#systemctl restart mysqld


## 安裝 自動外掛
yum -y install expect
## 安裝 wget
yum -y install wget



## 下載 github檔案
## /SH/bin/SH/MySQL.sh
wget https://raw.githubusercontent.com/moon-start/SH/master/binSH/MySQL.sh
###########
chmod 750 /root     ## drwxr-x---. 
chmod +x  ./MySQL.sh
# 因為expect用的不是bash所以會報錯。執行的時候直接./autosu.sh就可以了。～切記！
./MySQL.sh
rm -rf  MySQL.sh

