#!/bin/bash
systemctl enable --now cockpit.socket
#systemctl status cockpit.socket



### 安裝
yum -y install nginx


### 開機啟動
systemctl enable --now nginx
### 查看
# systemctl status nginx -l


### 防火牆
# 暫時設定(打開防火牆)
firewall-cmd --add-service=http
# 永久設定
firewall-cmd --add-service=http --permanent


# systemctl restart nginx ##重新啟動服務
# ls -al /usr/share/nginx/html
ln -s /usr/share/nginx/html /root/www




### 建立一個 /etc/nginx/nginx.conf
cd /etc/nginx
wget https://raw.githubusercontent.com/moon-start/SH/master/binSH/nginx.conf
### 建立一個 /etc/nginx/conf.d/default.conf
cd /etc/nginx/conf.d
wget https://raw.githubusercontent.com/moon-start/SH/master/binSH/default.conf
### 重新載入設定
systemctl reload nginx






