#!/bin/bash

# home =`pwd`  ## 顯示找不到指令!?

## 安裝 
yum -y install php php-fpm  php-json php-gd php-mbstring
# yum install php php-fpm php-json php-gd php-mbstring


##(只需修改需要的部份，其他的設定項目保留原狀)
#nano /etc/php-fpm.d/www.conf
#   user = nginx
#   group = nginx
#   listen = /run/php-fpm/www.sock
#   listen.acl_users = nginx
#   slowlog = /var/log/php-fpm/www-slow.log
#   php_admin_value[error_log] = /var/log/php-fpm/www-error.log
#   php_admin_flag[log_errors] = on

rm -rf /etc/php-fpm.d/www.conf
cd /etc/php-fpm.d
wget https://raw.githubusercontent.com/moon-start/SH/master/binSH/www.conf
chmod 644 /etc/php-fpm.d/www.conf
cd ~/

### 重新啟動 服務
# systemctl restart network.service
