#!/bin/bash

### 看这句提示，是因为缺少 package.json 这个文件。
### 初始化項目
npm init -f


## 這個必須要加上
##############################################
### 找不到要導入的樣式表。
### // Bootstrap
### @import '~bootstrap/scss/bootstrap';
### App.scss
### 產生失敗 /css/app.css 
npm install bootstrap
##########################################
cls 
### 編譯，把 \resources\assets\sass 
echo "編譯scss，專案/resources/sass目錄。"
npm install && npm run dev
echo "產生css，於\public\css的資料夾下，"


