#!/bin/bash

if   [ "$#" = "2" ]
then
    cd $2
    echo "666"
# elif [ "$#" = "1" ]
    
fi



# if [ -d "/path/to/dir" ]; then
#     # 目錄 /path/to/dir 存在
#     echo "Directory /path/to/dir exists."
# else
#     # 目錄 /path/to/dir 不存在
#     echo "Directory /path/to/dir does not exists."
# fi


QQ=`pwd`
echo "$QQ"
find $QQ -type d -name $1


## 取得上層目錄
# QQ=`pwd`
# echo "刪除 ${QQ##*/} 專案"



# ## 刪除
# cd ..
# rm -rf ./${QQ##*/}


# ## 下載
# cloneX ${QQ##*/}


# find . -name gtwang.txt

