#!/bin/bash



######
## 成功
## QQ變數
## $2 臨時切換變數 
############################
if   [ "$#" = "2" ]
then
    cd $2
    QQ=`pwd`
    find $QQ -type d -name $1
elif [ "$#" = "1" ]
    QQ=`pwd`
    find $QQ -type d -name $1
else
    echo "指令 [XX]  [指定path]"
fi





# if [ -d "/path/to/dir" ]; then
#     # 目錄 /path/to/dir 存在
#     echo "Directory /path/to/dir exists."
# else
#     # 目錄 /path/to/dir 不存在
#     echo "Directory /path/to/dir does not exists."
# fi

## 取得上層目錄
# QQ=`pwd`
# echo "刪除 ${QQ##*/} 專案"



# ## 刪除
# cd ..
# rm -rf ./${QQ##*/}


# ## 下載
# cloneX ${QQ##*/}


# find . -name gtwang.txt

