#!/bin/bash



## 下載 pass
wget https://raw.githubusercontent.com/moon-start/SH/master/binSQL/pass.sh
###########
chmod 750 /root     ## drwxr-x---. 
chmod +x  ./MySQL.sh
# 因為expect用的不是bash所以會報錯。執行的時候直接./autosu.sh就可以了。～切記！
./MySQL.sh
rm -rf  MySQL.sh

