#!/bin/bash





## 取得上層目錄 #########
QQ=`pwd`
QQA=${QQ##*/}

if   [ "$#" = "1" ]
then
########################

    ########################
    wget https://raw.githubusercontent.com/moon-start/SH/master/binSQL/moonPASS.sql
    # sed -i "s/moon/$1/g"  ./moonPASS.sql
    clear
    echo "你輸入你的 MySQL 密碼: "
    mysql -u root -p  <   ./moonPASS.sql
    rm -rf ./moonPASS.sql
    

else
    echo ""
    echo "說明 [指令] [資料庫的名稱]"
    echo ""
fi

