#!/bin/bash





## 取得上層目錄 #########
QQ=`pwd`
QQA=${QQ##*/}

if   [ "$#" = "1" ]
then
########################

    ########################
    wget https://raw.githubusercontent.com/moon-start/SH/master/binSQL/moonPASS.sql
    # sed -i "s/moon/$1/g"  ./moonPASS.sql
    clear
    echo "你輸入你的 MySQL 密碼: "
    mysql -u root -p  <   ./moonPASS.sql
    rm -rf ./moonPASS.sql
    

else
    echo ""
    echo "說明 [指令] [資料庫的名稱]"
    echo ""
fi


# ## 查看 user host
# use mysql;select user,host from user;


# ## show_validate_password
# SHOW VARIABLES LIKE 'validate_password%';
# ## 7.0
# ## SET GLOBAL validate_password_policy=LOW;
# ## 8.0
# SET GLOBAL validate_password.policy=LOW;

