#!/bin/bash



if [ ! -f  /etc/profile.QQ ] ; then
##################### >> 注意是附加 不要覆蓋
    echo "QQ=\`pwdQQ\`">>/etc/profile
    #echo "source /etc/profile">>/etc/profile

    echo "已經產生" > /etc/profile.QQ

else 
    echo "已經設定過~!!"
fi